n_classes: 1

encoder:
  n_layers: 14
  d_model: 384
  n_heads: 6
  dim_feedforward: 1152
  dropout: 0.1
  act: 'gelu'
  n_classes: ${n_classes}
  backbone:
    n_blocks: 4
    in_channels: 3
    inner_channels: 32
    out_channels: ${encoder.d_model}
    kernel_size: 3
    stride: 1
    padding: 1

train_dataset:
  manifest_path: '.'
  batch_size: 32
  shuffle: true
  num_workers: 4
  norm:
    mean: ${processor.mean}
    std: ${processor.std}
  flip: true

val_dataset:
  manifest_path: '.'
  batch_size: 32
  shuffle: false
  num_workers: 4
  norm:
    mean: ${processor.mean}
    std: ${processor.std}
  flip: false

processor:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

optimizer:
  lr: 0.0001
  betas: [0.9, 0.98]
  weight_decay: 1e-3
  model_size: ${encoder.d_model}
  warmup_steps: 1000
  factor: 0.01
